services:
  - type: web
    name: company-management-api
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: company-management-db
          property: connectionString
      - key: Jwt__Key
        value: "8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb"
      - key: Jwt__Issuer
        value: "https://company-management-api.onrender.com"
      - key: Jwt__Audience
        value: "https://simple-po-manager-dqeelw5qy-hemasais-projects.vercel.app"
      - key: ASPNETCORE_URLS
        value: "http://+:10000"
    healthCheckPath: /health
    autoDeploy: true
    plan: free

databases:
  - name: company-management-db
    databaseName: companymanagement
    user: companymanagement
    plan: free
    ipAllowList: [] 